name: Node.js CI

on:
  push:
    branches: [ master ]
    
defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      
      - name: Install Yarn/NPM dependencies
        run: yarn
        working-directory: ${{ env.working-directory }}
        
      - name: Run build
        run: yarn build
        working-directory: ${{ env.working-directory }}
        
      - name: Copy dist from Github to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./backend/dist"
          target: "test"
